### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by wyli**
trying to fix the mismatched checksum

https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=462519&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=531

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by wyli** [comment]
@conda-forge-admin, please rerender

**Comment by mdraw** [comment]
Hi @wyli, do you know why the checksum has changed for 0.8.1? When I released this version of the package initially the old checksum was working.

**Comment by mdraw** [comment]
It had worked in #2 but apparently failed on the master branch when it was merged. Strange. Since 0.8.1 actually never went live on the conda-forge package repository I guess it's fine to merge this without bumping the build number.

**Comment by wyli** [comment]
thanks, I don't know the root cause, apparently the commit that updates the checksum didn't pass the CI https://github.com/conda-forge/monai-feedstock/commit/30fdb718ff199b38eb009eec51d0ad9eaa59d2e3. We are in the process of releasing v0.9... I'll pay attention to this.

**Pull request merged**
